version: '3'

services:

  prometheus:
    image: prom/prometheus
    container_name: prometheus-container
    ports: 
      - 9090:9090
    networks: 
      - default

  grafana:
    image: grafana/grafana
    container_name: grafana-container
    ports: 
      - 3000:3000
    networks: 
      - default

networks: 
  default:
    external: 
      name: algamoney-network